<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuizMaster.Core\QuizMaster.Core.csproj" />
    <ProjectReference Include="..\QuizMaster.Service\QuizMaster.Service.csproj" />
  </ItemGroup>

</Project>
